---
title: "ahrf-2016-test"
output: html_document
---
# Usage

## There're 3230 rows and 6963 columns in the county file (wide format)

```{r, cache=TRUE, message=FALSE, warning=FALSE}
library(dplyr, warn.conflicts = FALSE)
library(Hmisc)
dim(ahrf_county)
```

## County-level hospital beds in 2013

```{r, message=FALSE, warning=FALSE, cache=TRUE}
ahrf_county %>% 
        select(county = F04437, 
               fips = F00002, 
               beds_2013 = F0892113,
               pop_2013 = F1198413) %>% 
        mutate(beds_2013 = as.integer(beds_2013),
               pop_2013 = as.integer(pop_2013),
               beds_2013_p10k = beds_2013 / pop_2013 * 10000) -> beds
beds
summary(beds$beds_2013)
summary(beds$pop_2013)
summary(beds$beds_2013_p10k)
quantile(beds$beds_2013_p10k, na.rm = TRUE)
```

## Geographic distribution of hospital beds in 2013

```{r bed-map, cache=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
beds$beds_2013_dist = Hmisc::cut2(beds$beds_2013_p10k, cuts = c(7.63, 20.50, 38.09))

#devtools::install_github("jjchern/usmapdata")
usmapdata::county %>% 
  left_join(beds, by = c("id" = "fips")) %>% 
        mutate(region = id) -> beds_map

usmapdata::state %>% 
        mutate(region = id) -> state_map

library(ggplot2)
library(viridis)
library(ggthemes)
ggplot() +
  geom_map(data = beds_map, map = beds_map,
           aes(x = long, y = lat, map_id = id, fill = beds_2013_dist),
           colour = alpha("white", 0.1), size=0.2) +
  geom_map(data = state_map, map = state_map,
           aes(x = long, y = lat, map_id = region),
           colour = "white", fill = "NA") +
  coord_map("albers", lat0 = 30, lat1 = 40) +
  viridis::scale_fill_viridis(discrete=TRUE, option = "D") +
  ggtitle("Hospital Beds per 10,000 Population in 2013") +
  ggthemes::theme_map() +
  theme(legend.position = c(.85, .3),
        legend.title=element_blank())
```
